version: '3.3'
services:
  db:
    image: mysql:8.0
    restart: always
    command:
      - --gtid-mode=ON
      - --enforce-gtid-consistency=ON
      - --log-slave-updates=ON
      - --binlog-format=ROW
      - --read-only=ON
      - --super-read-only=ON
      - --offline-mode=ON
      - --sync-binlog=1
      - --innodb-flush-log-at-trx-commit=1
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3306:3306'
      - '33060:33060'
    expose:
      # Opens port 3306 on the container
      - '3306'
      - '33060'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
# Names our volume
volumes:
  my-db:
